name: docs

on:
  pull_request_review:
    types: [submitted,edited]
  pull_request:
    branches:
      - master
      - develop
      - main
  push:
    branches:
      - develop
      - main


jobs:
  test-docstrings:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -qU pydocstyle

      - name: Check docstrings
        run: pydocstyle --convention=numpy mcmala

  build-and-deploy-pages:
    needs: test-docstrings
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 0 fetches complete history and tags

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -q -r docs/requirements.txt

      - name: Build API and docs
        run: |
          sphinx-apidoc -o docs/source/api mcmala
          sphinx-build -W --keep-going -b html -d docs/_build/doctrees docs/source docs/_build/html
          mv -v docs/_build/html public

      - name: Deploy
        if: ${{ github.event.review.state == 'approved' || github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
